config/routes.rb
AgileSchool::Application.routes.draw do

  root :to => 'students#index'

  get 'sponsors/modal'

  resources :sponsors

  resources :grades

  resources :series

  resources :classrooms

  resources :students

  
  

end

app/models/student.rb
class Student < ActiveRecord::Base

  attr_accessible :born_date, :name, :gender, :financial_sponsor
  
  enum_attr :gender, %w(masculino feminino)

  validates :name, :presence => true

  has_many :student_sponsors
  has_many :sponsors, :through => :student_sponsors

  has_one :financial_sponsor, :class_name => 'Sponsor', :foreign_key => 'id'


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
    
    

    
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    params[:sponsors].each do |id|
      if !id.empty? 
        @student.student_sponsors.build(:sponsor_id => id)
      end
    end

    @student.financial_sponsor = Sponsor.find(params[:financial_sponsor_id])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update

    @student = Student.find(params[:id])

    @student.student_sponsors.destroy_all

    params[:sponsors].each do |id|
      if !id.empty? 
        @student.student_sponsors.build(:sponsor_id => id)
        
      end
    end

    @student.financial_sponsor = Sponsor.find(params[:financial_sponsor_id])
    
    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student, :html => { :class => 'form-horizontal' } do |f| %>
<div class="control-group">
	<%= f.label :name, :class => 'control-label' %>
	<div class="controls">
		<%= f.text_field :name, :class => 'text_field' %>
	</div>
</div>
<div class="control-group">
	<%= f.label :born_date, :class => 'control-label' %>
	<div class="controls">
		<%= f.text_field :born_date, :class => 'date_select test', 'data-behaviour' => 'datepicker' %>

	</div>
</div>
<div class="control-group">
	<%= f.label 'Gênero', :class => 'control-label' %>
	<div class="controls">
		<%= f.enum_select :gender, :class => 'chosen_field' %>
	</div>
</div>

<div class="control-group">
	<%= f.label 'Responsáveis', :class => 'control-label' %>
	<div class="controls">

		<%= select_tag :sponsors, options_for_select( Sponsor.all.map { |s| [s.name, s.id] }, 
				@student.sponsors.map  { |j| j.id } ), 
				include_blank: true, :multiple => true, :style => 'width:90%;height:5%;display:none;', 
				:class => 'chosen_field'
		%>
 
		<a href="/sponsors/modal.html" role="button" class="btn" data-toggle="modal" data-target="#new-sponsor">Adicionar</a>
	</div>
</div>		
<div class="control-group">
	<%= f.label 'Responsável Financeiro', :class => 'control-label' %>
	<div class="controls">


		<%= select_tag :financial_sponsor_id, 
			options_for_select( 
				@student.sponsors.map { |s| [s.name, s.id] }, 
				[@student.financial_sponsor.nil? ? '' : '#@student.financial_sponsor.id'])
		%>
	</div>
</div>



<div class="form-actions">
	<%= f.submit nil, :class => 'btn btn-primary' %>
	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	students_path, :class => 'btn' %>
</div>
<% end %>

<div id="new-sponsor" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:born_date) %></th>
      <th><%= model_class.human_attribute_name(:sexo) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.id, student_path(student) %></td>
        <td><%= student.name %></td>
        <td><%= student.born_date %></td>
        <td><%= student.gender %></td>
        <td><%=l student.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Novo %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @student.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data_de_nascimento) %>:</strong></dt>
  <dd><%= @student.born_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gênero) %>:</strong></dt>
  <dd><%= @student.gender.to_s.titleize %></dd>
  <dt><strong><%= model_class.human_attribute_name(:responsáveis) %>:</strong></dt>
  <dd>
    <% @student.sponsors.each do |sponsor| %>
      <span><%= sponsor.name %></span></br>
    <% end %>  
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:responsável_financeiro) %>:</strong></dt>
  <dd><%= @student.financial_sponsor.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>