config/routes.rb
AgileSchool::Application.routes.draw do

  root :to => 'students#index'

  get 'sponsors/modal'

  resources :sponsors

  resources :grades

  resources :series

  resources :classrooms

  resources :students

  
  

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true

  has_many :student_sponsors
  has_many :students, :through => :student_sponsors

  belongs_to :student

end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController

  
  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sponsors }
    end
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/new
  # GET /sponsors/new.json
  def new
    @sponsor = Sponsor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/modal
  # GET /sponsors/modal.json
  def modal
    @sponsor = Sponsor.new

    render layout: false
  end

  # GET /sponsors/1/edit
  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(params[:sponsor])
    
    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render json: { data: @sponsor, notice: 'Sponsor was successfully created.'}, status: :created, location: @sponsor }
      else
        format.html { render action: "new" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sponsors/1
  # PUT /sponsors/1.json
  def update
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      if @sponsor.update_attributes(params[:sponsor])
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor = Sponsor.find(params[:id])
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to sponsors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<%= form_for @sponsor, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sponsors_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sponsors/_modal.html.erb
<%= form_for @sponsor, :html => { :class => 'form-modal' } do |f| %>
  
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Novo Responsável</h3>
    </div>
    <div class="modal-body">
        <div class="control-group">
          <%= f.label :name, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :name, :class => 'text_field' %>
          </div>
        </div>
    </div>
    <div class="modal-footer">
      
      <%= f.button nil, :class => 'btn btn-primary submit-modal' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  sponsors_path, :class => 'btn', 'data-dismiss' => "modal", 'aria-hidden' => "true" %>
    </div>
  
<% end %>

app/views/sponsors/edit.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sponsors/index.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sponsors.each do |sponsor| %>
      <tr>
        <td><%= link_to sponsor.id, sponsor_path(sponsor) %></td>
        <td><%= sponsor.name %></td>
        <td><%=l sponsor.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sponsor_path(sponsor), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sponsor_path(sponsor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sponsor_path,
            :class => 'btn btn-primary' %>

app/views/sponsors/modal.html.erb
<%= form_for @sponsor, :remote => true ,:format => :json, :html => { :class => 'form-horizontal form-modal' } do |f| %>
  
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Novo Responsável</h3>
    </div>
    <div class="modal-body">
        <div class="control-group">
          <%= f.label :name, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :name, :class => 'text_field' %>
          </div>
        </div>
    </div>
    <div class="modal-footer">
      
      <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
      <button class="btn btn-primary submit-modal">Salvar</button>
    </div>
  
<% end %>

app/views/sponsors/new.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sponsors/show.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @sponsor.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sponsors_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sponsor_path(@sponsor), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sponsor_path(@sponsor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>